p8105_hw2_pt2632
================
Pei Tian, pt2632
10/3/2023

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.3     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

## Problem 1

### Raw Datasets Processing

1.  `pols-month.csv`: 822 observations, 9 variables (Before processing)

    Variables:

    - `mon`: date of the count

    - `prez_gop`: indicator of whether the president was republican on
      the associated date (1 = yes, 0 = no)

    - `gov_gop`: the number of republican governors on the associated
      date

    - `sen_gop`: the number of republican senators on the associated
      date

    - `rep_gop`: the number of republican representatives on the
      associated date

    - `prez_dem`: indicator of whether the president was democratic on
      the associated date (1 = yes, 0 = no)

    - `gov_dem`: the number of democratic governors on the associated
      date

    - `sen_dem`: the number of democratic senators on the associated
      date

    - `rep_dem`: the number of democratic representatives on the
      associated date

``` r
# Tidy 'pols-month.csv'
pols <- 
  # load data
  read_csv("./datasets/HW2/fivethirtyeight_datasets/pols-month.csv") |> 
  # clean column name
  janitor::clean_names() |> 
  # separate date into 'year', 'month', 'day'
  separate(mon, c("year", "month","day"), convert = TRUE, sep = '-') |> 
  # change month number to month name
  mutate(month = month(month, label = TRUE), 
         # create 'president' variable according to value of 'prez_gop' variable
         president = recode(
           prez_gop, 
           "0" = "dem", 
           "1" = "gop",
           "2" = "gop"
         )) |>
  # remove some columns
  select(-c(day, prez_dem, prez_gop)) 
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

After processing, there are 822 observations and 9 variables in the
dataset.

The range of the `year` is between 1947 and 2015.

2.  `snp.csv`: 787 rows, 2 columns (Before processing)

    Variables:

    - `date`: the date of the observation

    - `close`: the closing values of the S&P stock index on the
      associated date

``` r
# Tidy 'snp.csv'
snp <- 
  # load data
  read_csv("./datasets/HW2/fivethirtyeight_datasets/snp.csv", 
           col_types = cols(date = col_date(format = "%m/%d/%y"))) |>
  # clean column name
  janitor::clean_names() |>  
  # separate date into 'year', 'month', 'day'
  separate(date, c("year", "month","day"), convert = TRUE) |>
  mutate(
    # change month number to month name
    month = month(month, label = TRUE),
    # change year format
    year = if_else(year > 2023, year - 100, year)) |> 
  # arrange columns
  arrange(year, month) |> 
  # remove some columns
  select(-day)
```

After processing, there are 787 observations and 3 variables in the
dataset.

The range of the `year` is between 1950 and 2015.

3.  `unemployment.csv`: 816 rows, 13 columns (Before processing)

    Variables:

    - `year`: year information

    - Others: unemployment rate of exact month

``` r
# Tidy 'unemployment.csv'
unemploy <- 
  # load data
  read.csv("./datasets/HW2/fivethirtyeight_datasets/unemployment.csv") |>
  # clean column name
  janitor::clean_names()  |>
  # switch "wide" to "long" format
  pivot_longer(-year, names_to = "month", values_to = "unemploy_rate") |> 
  # capitalize first letter to ensure same values in key variable
  mutate(month = str_to_title(month))  
```

After processing, there are 816 observations and 3 variables in the
dataset.

The range of the `year` is between 1948 and 2015.

### Data Merge

**Key variables:** use `year` and `month` variables to merge datasets.

``` r
# Join datasets (Merge)
res <- left_join(pols, snp, by = join_by(month == month, year == year))
res <- left_join(res, unemploy, by = join_by(month == month, year == year))
```

After combination, there are 822 observations and 11 variables in the
dataset.

The range of the `year` is between 1947 and 2015.

## Problem 2

### Raw Datasets Processing

1.  `Mr.Trash Wheel` sheet:

``` r
# Tidy "Mr.Trash Wheel" sheet in "202309 Trash Wheel Collection Data.xlsx"
trash1 <- 
  # load data, specify sheet + omit row with figure
  readxl::read_excel("./datasets/HW2/202309 Trash Wheel Collection Data.xlsx", sheet = 1, skip = 1) |> 
  # clean column name
  janitor::clean_names() |>
  # omit columns with notes
  janitor::remove_empty(which = "cols") |>
  # omit rows that do not include dumpster-specific data
  filter(!is.na(dumpster)) |>
  # calculate 'houses_powered' variable, houses_powered = 500 * weight_tons + 30
  mutate(homes_powered = 500 * weight_tons + 30,
         # convert type of year into 'character'
         year = as.character(year))
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

After processing, there are 584 observations and 14 variables in the
dataset.

Variables:

- `dumpster`: dumpster id

- `month`, `year`, `date`: date information

- `weight_tons`: collected trash weight

- `volume_cubic_yards`: trash volume

- `plastic_bottles`, `polystyrene`, `cigarette_butts`, `glass_bottles`,
  `grocery_bags`, `chip_bags`, `sports_balls`: specific trash amount

- `homes_powered`: power amount

2.  `Professor Trash Wheel` sheet:

``` r
# Tidy "Professor Trash Wheel" sheet in "202309 Trash Wheel Collection Data.xlsx"
trash2 <- 
  # load data, specify sheet + omit row with figure
  readxl::read_excel("./datasets/HW2/202309 Trash Wheel Collection Data.xlsx", sheet = 2, skip = 1) |> 
  # clean column name
  janitor::clean_names() |>
  # omit columns with notes
  janitor::remove_empty(which = "cols") |>
  # omit rows that do not include dumpster-specific data
  filter(!is.na(dumpster)) |>
  # calculate 'houses_powered' variable, houses_powered = 500 * weight_tons + 30
  mutate(homes_powered = 500 * weight_tons + 30,
         # convert type of year into 'character'
         year = as.character(year))
```

After processing, there are 106 observations and 13 variables in the
dataset.

Variables:

- `dumpster`: dumpster id

- `month`, `year`, `date`: date information

- `weight_tons`: collected trash weight

- `volume_cubic_yards`: trash volume

- `plastic_bottles`, `polystyrene`, `cigarette_butts`, `glass_bottles`,
  `grocery_bags`, `chip_bags`: specific trash amount

- `homes_powered`: power amount

3.  `Gwynnda Trash Wheel` sheet:

``` r
# Tidy "Gwynnda Trash Wheel" sheet in "202309 Trash Wheel Collection Data.xlsx"
trash3 <- 
  # load data, specify sheet + omit row with figure
  readxl::read_excel("./datasets/HW2/202309 Trash Wheel Collection Data.xlsx", sheet = 3, skip = 1) |> 
  # clean column name
  janitor::clean_names() |>
  # omit columns with notes
  janitor::remove_empty(which = "cols") |>
  # omit rows that do not include dumpster-specific data
  filter(!is.na(dumpster)) |>
  # calculate 'houses_powered' variable, houses_powered = 500 * weight_tons + 30
  mutate(homes_powered = 500 * weight_tons + 30,
         # convert type of year into 'character'
         year = as.character(year))
```

After processing, there are 28 observations and 12 variables in the
dataset.

Variables:

- `dumpster`: dumpster id

- `month`, `year`, `date`: date information

- `weight_tons`: collected trash weight

- `volume_cubic_yards`: trash volume

- `plastic_bottles`, `polystyrene`, `cigarette_butts`, `glass_bottles`,
  `plastic_bags`: specific trash amount

- `homes_powered`: power amount

### Data Combination

``` r
# combine datasets into single dataset
total_trash <- bind_rows(
  list("Mr. Trash Wheel" = trash1, 
       "Professor Trash Wheel" = trash2, 
       "Gwynnda Trash Wheel" = trash3), .id = "source")
```

After row binding process, there are 718 observations and 15 variables
in the dataset.

Specific questions:

The total weight of trash collected by Professor Trash Wheel equals to
216.26.

The total number of cigarette butts collected by Gwynnda in July of 2021
equals to 3200.

## Problem 3

### Demographic Dataset

``` r
baseline <- 
  # load data
  read_csv("./datasets/HW2/data_mci/MCI_baseline.csv", skip = 1) |> 
  # clean column name
  janitor::clean_names() |>
  # 'sex' and 'apoe4' variable as string
  mutate(sex = recode(sex, "0" = "Female", "1" = "Male"), 
         apoe4 = recode(apoe4, "0" = "non-carrier", "1" = "carrier"))
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

There are 483 observations and 6 variables in this dataset.

There are 483 participants are recruited.

The average age of baseline is 65.0467909.

There are 29.8578199% of women in the study are APOE4 carriers.

``` r
# remove participants with no MCI
mci_baseline <- filter(baseline, age_at_onset != ".")
mci_baseline
```

    ## # A tibble: 97 × 6
    ##       id current_age sex    education apoe4       age_at_onset
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>       <chr>       
    ##  1     3        62.5 Male          16 carrier     66.8        
    ##  2     5        66   Male          16 non-carrier 68.7        
    ##  3     7        66.5 Male          18 non-carrier 74          
    ##  4    13        63.1 Male          12 carrier     69          
    ##  5    14        58.4 Female        20 non-carrier 66.2        
    ##  6    18        67.8 Male          16 non-carrier 69.8        
    ##  7    22        67.3 Female        20 carrier     74.6        
    ##  8    26        64.8 Female        20 carrier     71.1        
    ##  9    30        66.3 Female        12 non-carrier 73.1        
    ## 10    39        68.3 Female        16 carrier     70.2        
    ## # ℹ 87 more rows

After processing, there are 97 observations and 6 variables.

And there are 97 participants developed MCI.

### Biomarker Dataset

``` r
amyloid <- 
  # load data
  read_csv("./datasets/HW2/data_mci/mci_amyloid.csv", skip = 1) |>
  # clean column name
  janitor::clean_names()  
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

There are 487 observations and 6 variables in this dataset.

### Data Combination

``` r
# check whether some participants appear in only the baseline or amyloid datasets
both_id <- intersect(pull(baseline, id), pull(amyloid, study_id))
# baseline
only_baseline <- c()
for(id in pull(baseline, id)){
  if (!id %in% both_id)
    only_baseline <- append(only_baseline, id)
}
# amyloid
only_amyloid <- c()
for(id in pull(amyloid, study_id)){
  if (!id %in% both_id)
    only_amyloid <- append(only_amyloid, id)
}
only_baseline
```

    ## [1]  14  49  92 179 268 304 389 412

``` r
only_amyloid
```

    ##  [1] 484 485 486 487 488 489 490 491 492 493 494 495

There are 8 participants only in baseline dataset, and 12 participants
only in amyloid dataset.

``` r
# combine datasets
participants <- inner_join(baseline, amyloid, by = join_by(id == study_id))
participants
```

    ## # A tibble: 475 × 11
    ##       id current_age sex    education apoe4  age_at_onset baseline time_2 time_4
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>  <chr>        <chr>    <chr>  <chr> 
    ##  1     1        63.1 Female        16 carri… .            0.11054… <NA>   0.109…
    ##  2     2        65.6 Female        20 carri… .            0.10748… 0.109… 0.109…
    ##  3     3        62.5 Male          16 carri… 66.8         0.10608… 0.108… 0.106…
    ##  4     4        69.8 Female        16 non-c… .            0.10925… 0.108… 0.110…
    ##  5     5        66   Male          16 non-c… 68.7         0.10795… 0.112… 0.115…
    ##  6     6        62.5 Male          16 non-c… .            0.11242… 0.112… 0.111…
    ##  7     7        66.5 Male          18 non-c… 74           0.11224… <NA>   0.104…
    ##  8     8        67.2 Female        18 non-c… .            0.10956… 0.109… <NA>  
    ##  9     9        66.7 Female        16 non-c… .            0.11210… 0.109… 0.108…
    ## 10    10        64.1 Female        18 non-c… .            0.11160… 0.111… <NA>  
    ## # ℹ 465 more rows
    ## # ℹ 2 more variables: time_6 <chr>, time_8 <chr>

After combining datasets with `id` variable, the result are of 475
observations and 11 variables.

``` r
# write combined data as csv file
write_csv(participants, "./output/hw2_problem3_output.csv")
```
